// Firebase Authentication + Firestore only. Storage and Analytics are intentionally not used.
const USE_FIREBASE=true;
const firebaseConfig={
  apiKey:"AIzaSyD5KNWxF0Uwugkoa7mN9dmvIYc-ZSuFZ-o",
  authDomain:"sonvarshi-devi-bhawan.firebaseapp.com",
  projectId:"sonvarshi-devi-bhawan",
  messagingSenderId:"387855978379",
  appId:"1:387855978379:web:8143bce8de616b03b6298e",
  measurementId:"G-D3CPZ3485R"
};
let fb=null;
if(USE_FIREBASE){
  const appMod=await import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js');
  const authMod=await import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js');
  const fsMod=await import('https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js');
  const app=appMod.initializeApp(firebaseConfig); fb={...authMod,...fsMod,auth:authMod.getAuth(app),db:fsMod.getFirestore(app)};
}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let month=new Date(); month.setDate(1); let state={tenants:[],payments:[],readings:[],milkCustomers:[],milkEntries:[],expenses:[],labour:[],debts:[],contacts:[]};
const key=()=>`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`;
function loadLocal(){state=JSON.parse(localStorage.getItem('sonvashi-data')||JSON.stringify(state))} function saveLocal(){localStorage.setItem('sonvashi-data',JSON.stringify(state));render()}
async function load(){ if(!USE_FIREBASE){loadLocal();state.labour||=[];state.debts||=[];render();return} const snap=await fb.getDocs(fb.collection(fb.db,'homeData')); state={tenants:[],payments:[],readings:[],milkCustomers:[],milkEntries:[],expenses:[],labour:[],debts:[],contacts:[]};snap.forEach(d=>{let x=d.data();(state[x.type]||=[]).push({id:d.id,...x})});render() }
async function persist(type,obj){if(!USE_FIREBASE){obj.id=obj.id||crypto.randomUUID();let a=state[type],i=a.findIndex(x=>x.id===obj.id);i>=0?a[i]=obj:a.push(obj);saveLocal();return} let data={...obj,type};delete data.id;obj.id?await fb.setDoc(fb.doc(fb.db,'homeData',obj.id),data):await fb.addDoc(fb.collection(fb.db,'homeData'),data);await load()}
async function remove(type,id){if(!confirm('Delete this record?'))return;if(!USE_FIREBASE){state[type]=state[type].filter(x=>x.id!==id);saveLocal()}else{await fb.deleteDoc(fb.doc(fb.db,'homeData',id));await load()}}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})} function monthName(){return month.toLocaleString('en-IN',{month:'long',year:'numeric'})}
function milkTotal(e){return +(e.morning??e.litres??0)+ +(e.evening||0)}
function render(){ $('#monthLabel').textContent=monthName(); let k=key(); let active=state.tenants.filter(t=>t.active!==false);let expected=active.reduce((s,t)=>s+ +t.rent,0);let paid=state.payments.filter(p=>p.month===k).reduce((s,p)=>s+ +p.amount,0);let elec=state.readings.filter(r=>r.month===k).reduce((s,r)=>s+(+r.current-+r.previous)*+r.rate,0);let me=state.milkEntries.filter(e=>e.date?.startsWith(k));let litres=me.reduce((s,e)=>s+milkTotal(e),0);let rev=me.reduce((s,e)=>{let c=state.milkCustomers.find(c=>c.id===e.customerId);return s+(milkTotal(e)*(+c?.price||0))},0);let ex=state.expenses.filter(e=>e.date?.startsWith(k)).reduce((s,e)=>s+ +e.amount,0);$('#rentReceived').textContent=money(paid);$('#rentDue').textContent=money(Math.max(0,expected-paid));$('#electricityTotal').textContent=money(elec);$('#milkLitres').textContent=litres+' L';$('#milkRevenue').textContent=money(rev);$('#expenseTotal').textContent=money(ex);renderTenants();renderReadings();renderMilk();renderExpenses();renderMoney();renderContacts()}
function item(title,sub,right,actions=''){return `<div class='item'><div class='row'><div><b>${title}</b><div class='muted'>${sub}</div></div><div class='amount'>${right}</div></div>${actions}</div>`}
function renderTenants(){let k=key();$('#tenantList').innerHTML=state.tenants.map(t=>{let p=state.payments.filter(x=>x.tenantId===t.id&&x.month===k).reduce((s,x)=>s+ +x.amount,0);return item(t.name,`Floor ${t.floor} · Rent ${money(t.rent)}`,`<span class='${p>=t.rent?'paid':'due'}'>${p>=t.rent?'Paid':money(t.rent-p)+' due'}</span>`,`<div class='miniActions'><button onclick="payTenant('${t.id}')">Add payment</button><button class='ghost' onclick="editTenant('${t.id}')">Edit</button><button class='danger' onclick="del('tenants','${t.id}')">Delete</button></div>`) }).join('')||'<p class="muted">No tenants yet.</p>'}
function renderReadings(){let k=key();$('#electricityList').innerHTML=state.readings.filter(r=>r.month===k).map(r=>{let units=+r.current-+r.previous,bill=units*+r.rate,people=+r.people||1;return item(`Floor ${r.floor}`,`${r.previous} → ${r.current} · ${units} units · ${money(r.rate)}/unit`,money(bill)+`<small> / ${people} = ${money(bill/people)}</small>`,`<div class='miniActions'><button class='danger' onclick="del('readings','${r.id}')">Delete</button></div>`) }).join('')||'<p class="muted">No reading for this month.</p>'}
function renderMilk(){let date=$('#milkDate').value||new Date().toISOString().slice(0,10);$('#milkDate').value=date;$('#dailyMilk').innerHTML=state.milkCustomers.map(c=>{let e=state.milkEntries.find(e=>e.customerId===c.id&&e.date===date);return `<div class='milkEntry'><div><b>${c.name}</b><small> · ${money(c.price)}/L</small></div><input type='number' min='0' step='.25' data-morning='${c.id}' value='${e?.morning??e?.litres??''}' placeholder='AM'><input type='number' min='0' step='.25' data-evening='${c.id}' value='${e?.evening??''}' placeholder='PM'></div>`}).join('')||'<p class="muted">Add a milk customer first.</p>';let k=key();$('#milkCustomers').innerHTML=state.milkCustomers.map(c=>{let ls=state.milkEntries.filter(e=>e.customerId===c.id&&e.date.startsWith(k)).reduce((s,e)=>s+milkTotal(e),0);return item(c.name,`${ls} L this month · ${money(c.price)}/L`,money(ls*c.price),`<div class='miniActions'><button class='ghost' onclick="editMilkCustomer('${c.id}')">Edit</button><button class='danger' onclick="del('milkCustomers','${c.id}')">Delete</button></div>`) }).join('');let selected=$('#calendarCustomer').value||state.milkCustomers[0]?.id||'';$('#calendarCustomer').innerHTML=state.milkCustomers.map(c=>`<option value='${c.id}' ${c.id===selected?'selected':''}>${c.name}</option>`).join('');renderMilkCalendar(selected)}
function renderMilkCalendar(customerId){let first=new Date(month.getFullYear(),month.getMonth(),1),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),cells=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class='calLabel'>${x}</div>`);for(let i=0;i<first.getDay();i++)cells.push(`<div class='calDay empty'></div>`);for(let d=1;d<=days;d++){let ds=`${key()}-${String(d).padStart(2,'0')}`,e=state.milkEntries.find(x=>x.customerId===customerId&&x.date===ds),am=+(e?.morning??e?.litres??0),pm=+(e?.evening||0);cells.push(`<div class='calDay ${am+pm?'hasMilk':''}'><b>${d}</b><span>AM ${am||'-'}</span><br><span>PM ${pm||'-'}</span><div class='total'>${am+pm?am+pm+' L':''}</div></div>`)}$('#milkCalendar').innerHTML=`<div class='calendarGrid'>${cells.join('')}</div>`}
function renderMoney(){let k=key();let labour=state.labour.filter(x=>x.date?.startsWith(k));$('#labourList').innerHTML=labour.map(x=>{let total=+x.days*+x.perDay,due=Math.max(0,total-(+x.paid||0));return item(x.name,`${x.date} · ${x.days} day(s) × ${money(x.perDay)}`,`${money(total)}<small class='${due?'due':'paid'}'>${due?money(due)+' due':' Paid'}</small>`,`<div class='miniActions'><button onclick="payLabour('${x.id}')">Add paid</button><button class='danger' onclick="del('labour','${x.id}')">Delete</button></div>`) }).join('')||'<p class="muted">No labour work this month.</p>';let debts=state.debts.filter(x=>x.date?.startsWith(k));let pay=debts.filter(x=>x.direction==='Pay'&&!x.settled).reduce((s,x)=>s+ +x.amount,0),receive=debts.filter(x=>x.direction==='Receive'&&!x.settled).reduce((s,x)=>s+ +x.amount,0);$('#debtList').innerHTML=`<div class='balance'><span class='pill red'>To pay ${money(pay)}</span><span class='pill green'>To receive ${money(receive)}</span></div>`+debts.map(x=>item(x.name,`${x.date} · ${x.direction}${x.note?' · '+x.note:''}`,`<span class='${x.settled?'paid':x.direction==='Pay'?'due':'paid'}'>${money(x.amount)}${x.settled?' ✓':''}</span>`,`<div class='miniActions'><button class='ghost' onclick="settleDebt('${x.id}')">${x.settled?'Mark pending':'Mark settled'}</button><button class='danger' onclick="del('debts','${x.id}')">Delete</button></div>`)).join('')}
function renderExpenses(){let k=key();$('#expenseList').innerHTML=state.expenses.filter(e=>e.date.startsWith(k)).sort((a,b)=>b.date.localeCompare(a.date)).map(e=>item(e.title,`${e.date} · ${e.category}`,money(e.amount),`<div class='miniActions'><button class='danger' onclick="del('expenses','${e.id}')">Delete</button></div>`)).join('')||'<p class="muted">No expenses this month.</p>'}
function renderContacts(){let q=$('#contactSearch').value.toLowerCase();$('#contactList').innerHTML=state.contacts.filter(c=>(c.name+c.category).toLowerCase().includes(q)).map(c=>item(c.name,c.category,c.phone?`<a href='tel:${c.phone}'>${c.phone}</a>`:'',`<div class='miniActions'><button class='danger' onclick="del('contacts','${c.id}')">Delete</button></div>`)).join('')||'<p class="muted">No contacts found.</p>'}
let submitFn=null;function modal(title,fields,onSave){$('#modalTitle').textContent=title;$('#modalFields').innerHTML=fields;submitFn=onSave;$('#modal').showModal()} $('#cancelModal').onclick=()=>$('#modal').close();$('#modalForm').onsubmit=e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));submitFn(data);$('#modal').close()}
$('#addTenant').onclick=()=>modal('Add tenant',`<input name='name' required placeholder='Name'><input name='phone' placeholder='Phone'><select name='floor'><option>2</option><option>3</option></select><input name='rent' type='number' required placeholder='Monthly rent'>`,d=>persist('tenants',{...d,rent:+d.rent}));
window.editTenant=id=>{let t=state.tenants.find(x=>x.id===id);modal('Edit tenant',`<input name='name' value='${t.name}' required><input name='phone' value='${t.phone||''}'><select name='floor'><option ${t.floor==2?'selected':''}>2</option><option ${t.floor==3?'selected':''}>3</option></select><input name='rent' type='number' value='${t.rent}' required>`,d=>persist('tenants',{...t,...d,rent:+d.rent}))};window.payTenant=id=>modal('Add rent payment',`<input name='amount' type='number' required placeholder='Amount'><input name='date' type='date' value='${new Date().toISOString().slice(0,10)}' required>`,d=>persist('payments',{tenantId:id,month:key(),amount:+d.amount,date:d.date}));
$('#addReading').onclick=()=>modal('Meter reading',`<select name='floor'><option>2</option><option>3</option></select><input name='previous' type='number' required placeholder='Previous reading'><input name='current' type='number' required placeholder='Current reading'><input name='rate' type='number' step='.01' required placeholder='₹ per unit'><input name='people' type='number' required placeholder='People sharing'>`,d=>persist('readings',{...d,month:key()}));
$('#addMilkCustomer').onclick=()=>modal('Milk customer',`<input name='name' required placeholder='Customer name'><input name='phone' placeholder='Phone'><input name='price' type='number' step='.01' required placeholder='Price per litre'>`,d=>persist('milkCustomers',{...d,price:+d.price}));window.editMilkCustomer=id=>{let c=state.milkCustomers.find(x=>x.id===id);modal('Edit milk customer',`<input name='name' value='${c.name}' required><input name='phone' value='${c.phone||''}'><input name='price' type='number' step='.01' value='${c.price}' required>`,d=>persist('milkCustomers',{...c,...d,price:+d.price}))};$('#milkDate').onchange=renderMilk;$('#calendarCustomer').onchange=e=>renderMilkCalendar(e.target.value);$('#saveMilk').onclick=async()=>{let date=$('#milkDate').value;for(let i of $$('[data-morning]')){let id=i.dataset.morning,pm=$(`[data-evening='${id}']`),old=state.milkEntries.find(e=>e.customerId===id&&e.date===date);if(i.value!==''||pm.value!=='')await persist('milkEntries',{...(old||{}),customerId:id,date,morning:+i.value||0,evening:+pm.value||0})}render()};
$('#addExpense').onclick=()=>modal('Add expense',`<input name='title' required placeholder='Expense'><select name='category'><option>House</option><option>Milk</option><option>Cow</option><option>Repair</option><option>Other</option></select><input name='amount' type='number' required placeholder='Amount'><input name='date' type='date' value='${new Date().toISOString().slice(0,10)}' required>`,d=>persist('expenses',{...d,amount:+d.amount}));$('#addContact').onclick=()=>modal('Add contact',`<input name='name' required placeholder='Name'><select name='category'><option>Electrician</option><option>Plumber</option><option>Carpenter</option><option>Mason</option><option>Painter</option><option>AC Repair</option><option>RO Repair</option><option>Other</option></select><input name='phone' placeholder='Phone'>`,d=>persist('contacts',d));$('#contactSearch').oninput=renderContacts;window.del=remove;
$('#addLabour').onclick=()=>modal('Add labour work',`<input name='name' required placeholder='Labour name'><input name='date' type='date' value='${new Date().toISOString().slice(0,10)}' required><input name='days' type='number' min='.5' step='.5' value='1' required placeholder='Days worked'><input name='perDay' type='number' required placeholder='Wage per day'><input name='paid' type='number' value='0' placeholder='Already paid'>`,d=>persist('labour',{...d,days:+d.days,perDay:+d.perDay,paid:+d.paid||0}));window.payLabour=id=>{let x=state.labour.find(v=>v.id===id);modal('Add labour payment',`<input name='amount' type='number' required placeholder='Amount paid'>`,d=>persist('labour',{...x,paid:(+x.paid||0)+ +d.amount}))};$('#addDebt').onclick=()=>modal('Add money entry',`<input name='name' required placeholder='Person name'><select name='direction'><option>Pay</option><option>Receive</option></select><input name='amount' type='number' required placeholder='Amount'><input name='date' type='date' value='${new Date().toISOString().slice(0,10)}' required><input name='note' placeholder='Reason / note'>`,d=>persist('debts',{...d,amount:+d.amount,settled:false}));window.settleDebt=id=>{let x=state.debts.find(v=>v.id===id);persist('debts',{...x,settled:!x.settled})};
function go(p){$$('.page').forEach(x=>x.classList.toggle('active',x.id===p));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p))}$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);render()};$('#nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);render()};
async function showApp(){ $('#login').hidden=true;$('#app').hidden=false;go('home');await load() } $('#loginBtn').onclick=async()=>{if(!USE_FIREBASE){showApp();return}try{await fb.signInWithEmailAndPassword(fb.auth,$('#email').value,$('#password').value)}catch(e){alert('Login failed: '+e.message)}};$('#logout').onclick=async()=>{if(USE_FIREBASE)await fb.signOut(fb.auth);location.reload()};if(!USE_FIREBASE)showApp();else fb.onAuthStateChanged(fb.auth,user=>{if(user)showApp()});
